export const PATHS = {
  HOME: "/",
  ROOMS: "/rooms",
  ROOM_DETAIL: "/rooms/:id",
  BRANCHES: "/branches",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",

  CUSTOMER_HOME: "/customer/home",
  CUSTOMER_ROOMS: "/customer/rooms",
  CUSTOMER_ROOM_DETAIL: "/customer/rooms/:id",
  CUSTOMER_BOOKING_CREATE: "/customer/booking/create",
  CUSTOMER_BOOKING_REVIEW: "/customer/booking/review",
  CUSTOMER_BOOKING_PAYMENT: "/customer/booking/payment",
  CUSTOMER_BOOKING_RESULT: "/customer/booking/result",
  CUSTOMER_BOOKING_SUCCESS: "/customer/booking/result/success",
  CUSTOMER_BOOKING_FAILED: "/customer/booking/result/failed",
  CUSTOMER_BOOKINGS: "/customer/bookings",
  CUSTOMER_BOOKING_DETAIL: "/customer/bookings/:id",
  CUSTOMER_PROFILE: "/customer/profile",
  CUSTOMER_PROFILE_EDIT: "/customer/profile/edit",
  CUSTOMER_SETTINGS: "/customer/settings",
  CUSTOMER_SETTINGS_ADVANCED: "/customer/settings/advanced",
  CUSTOMER_FEEDBACK_CREATE: "/customer/bookings/feedbacks/create",
  CUSTOMER_FEEDBACKS: "/customer/bookings/feedbacks",

  STAFF: "/staff",
  STAFF_BOOKINGS_TODAY: "/staff/bookings/today",
  STAFF_CHECKIN: "/staff/checkin/:id",
  STAFF_CHECKOUT: "/staff/checkout/:id",
  STAFF_ROOMS_STATUS: "/staff/rooms/status",
  STAFF_SERVICE_USAGE: "/staff/service-usage",

  MANAGER: "/manager",
  MANAGER_ROOMS: "/manager/rooms",
  MANAGER_ROOMS_CREATE: "/manager/rooms/create",
  MANAGER_ROOMS_EDIT: "/manager/rooms/:id/edit",
  MANAGER_BOOKINGS: "/manager/bookings",
  MANAGER_BOOKINGS_DETAIL: "/manager/bookings/:id",
  MANAGER_STAFF: "/manager/staff",
  MANAGER_FEEDBACKS: "/manager/feedbacks",
  MANAGER_SERVICES: "/manager/services",
  MANAGER_PRICING_REQUESTS: "/manager/pricing-requests",

  OWNER: "/owner",
  OWNER_BRANCHES: "/owner/branches",
  OWNER_BOOKINGS: "/owner/bookings",
  OWNER_PRICING: "/owner/pricing",
  OWNER_PRICING_REQUESTS: "/owner/pricing-requests",
  OWNER_USERS: "/owner/users",
  OWNER_LOGS: "/owner/logs",

  FORBIDDEN: "/forbidden"
};
