const PATHS = {
  ROOT: '/',
  PUBLIC: {
    HOME: '/',
    ABOUT: '/about',
    CONTACT: '/contact',
    ROOM_LIST: '/rooms',
    ROOM_DETAIL: '/rooms/:id',
  },
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    VERIFY_EMAIL: '/verify-email',
  },
  CUSTOMER: {
    BASE: '/customer',
    HOME: '/customer',
    SEARCH: '/customer/search',
    ROOM_DETAIL: '/customer/rooms/:id',
    BOOKING_CREATE: '/customer/booking/create',
    BOOKING_REVIEW: '/customer/booking/review',
    BOOKING_PAYMENT: '/customer/booking/payment',
    BOOKING_SUCCESS: '/customer/booking/success',
    BOOKING_LIST: '/customer/bookings',
    BOOKING_DETAIL: '/customer/bookings/:id',
    PROFILE: '/customer/profile',
    PROFILE_EDIT: '/customer/profile/edit',
    CHANGE_PASSWORD: '/customer/settings/password',
    FEEDBACK_CREATE: '/customer/feedbacks/create',
    MY_FEEDBACKS: '/customer/feedbacks',
  },
  STAFF: {
    BASE: '/staff',
    DASHBOARD: '/staff',
    TODAY_BOOKINGS: '/staff/bookings/today',
    CHECKIN: '/staff/checkin',
    CHECKOUT: '/staff/checkout',
    ROOM_STATUS: '/staff/rooms/status',
    SERVICE_USAGE: '/staff/service-usage',
  },
  MANAGER: {
    BASE: '/manager',
    DASHBOARD: '/manager',
    ROOMS: '/manager/rooms',
    ROOM_CREATE: '/manager/rooms/create',
    ROOM_EDIT: '/manager/rooms/:id/edit',
    BOOKINGS: '/manager/bookings',
    BOOKING_DETAIL: '/manager/bookings/:id',
    FEEDBACKS: '/manager/feedbacks',
    REPLY_FEEDBACK: '/manager/feedbacks/reply',
    SERVICES: '/manager/services',
    SERVICE_CREATE: '/manager/services/create',
    SERVICE_EDIT: '/manager/services/:id/edit',
    PRICING_REQUESTS: '/manager/pricing-requests',
    PRICING_REQUEST_CREATE: '/manager/pricing-requests/create',
    REPORT_REVENUE: '/manager/reports/revenue',
    REPORT_BOOKING: '/manager/reports/booking',
  },
  OWNER: {
    BASE: '/owner',
    DASHBOARD: '/owner',
    BRANCHES: '/owner/branches',
    BRANCH_CREATE: '/owner/branches/create',
    BRANCH_EDIT: '/owner/branches/:id/edit',
    PRICING: '/owner/pricing',
    PRICING_CREATE: '/owner/pricing/create',
    PRICING_EDIT: '/owner/pricing/:id/edit',
    PRICING_REQUESTS: '/owner/pricing-requests',
    APPROVE_REQUEST: '/owner/pricing-requests/:id/approve',
    REJECT_REQUEST: '/owner/pricing-requests/:id/reject',
    USERS: '/owner/users',
    ROLE_MANAGEMENT: '/owner/users/roles',
    REPORT_GLOBAL: '/owner/reports/revenue',
    REPORT_BRANCH: '/owner/reports/branches',
    SYSTEM_LOGS: '/owner/logs',
  },
  FALLBACK: '*',
};
export default PATHS;
