const BOOKING_STATUS = {
	HOLD: 'HOLD',
	CONFIRMED: 'CONFIRMED',
	CHECKED_IN: 'CHECKED_IN',
	CHECKED_OUT: 'CHECKED_OUT',
	CANCELLED: 'CANCELLED',
	EXPIRED: 'EXPIRED'
};

export default BOOKING_STATUS;
