spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/hotel}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/hotel}
      database: ${MONGODB_DATABASE:hotel}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://luxstay.phanvanduong.site}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your_email@gmail.com}
    password: ${MAIL_PASSWORD:your_password}
    from: ${MAIL_FROM:${MAIL_USERNAME}}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
          connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
          timeout: ${MAIL_SMTP_TIMEOUT:5000}
          writetimeout: ${MAIL_SMTP_WRITE_TIMEOUT:5000}

logging:
  level:
    root: INFO
    org.springframework: INFO
